### ISSUE TITLE
Requirements Dependency not Found in PyPi

### ISSUE THREAD

**Issue by skchronicles** [snakemake/snakeface#14]
### About 
I believe you have a typo for one of the dependencies in your `requirements.txt` file.

It is erroring out when trying to resolve the following dependency: `django-taggie`
```
ERROR: Could not find a version that satisfies the requirement django-taggie
ERROR: No matching distribution found for django-taggie
```
### Resolves Issue
I checked PyPi and I do not saw a package with that name. it looks like this may be a typo. Did you mean to include `django-taggit==1.3.0` instead?
![image](https://user-images.githubusercontent.com/18038345/107567252-8afbae00-6bb3-11eb-90c5-76bb25176e21.png)

**Comment by vsoch** [comment]
That's a typo! it should be taggit. Ironically, just as I was typing that I typed "Taggie" again, must be muscle memory!

**Comment by vsoch** [comment]
And... I did it again in the comment! :laughing: https://github.com/snakemake/snakeface/commit/53ad109cc860137c6c0a3429cf2dc6629ada716a But it should be fixed now in main :)

**Comment by skchronicles** [comment]
Thanks, I appreciate it!

**Comment by vsoch** [comment]
Awesome! And thanks for taking a look - this is definitely a work in progress, and we can continue developing when there is more testing and feedback as to how it is now. For example, I think the workflow creation form could be better consolidated into something more dense, and there are a few other issues open (e.g., #13) that will improve functionality greatly.
