### ISSUE TITLE
Instructions to run a pipeline via snakeface

### ISSUE THREAD

**Issue by fgypas** [snakemake/snakeface#19]
Hi @vsoch 

Can you please tell me how can I run a simple pipeline via snakeface?

When I run something like the following:
```bash
snakeface \
--port 5432 \
https://github.com/panoptes-organization/snakemake_example_workflow \
this_is_a_test \
notebook
```

I get a message:

> You don't have any Snakemake workflows. Why don't you create one?

And when I click on `create one` I get a message:

> No Snakefiles were found in any path under /Users/gypafoiv/Desktop/snakeface. You must have one to create a workflow.

What am I doing wrong?

Thank you in advance

**Comment by vsoch** [comment]
I'm not sure why you are adding a GitHub url to the command (it could be a use case but is not developed yet). You would need to have a Snakefile in the root or somewhere in a subfolder where you run Snakeface. So you can take this verbatim:

> No Snakefiles were found in any path under /Users/gypafoiv/Desktop/snakeface. You must have one to create a workflow.

**Comment by vsoch** [comment]
Where did you read to formulate that command? And what is `this_is_a_test` and `notebook`?

**Comment by vsoch** [comment]
Instead of having it work like an ipython notebook to look for files already existing, we could have it work to provide a url with a workflow and then the workflow is cloned somewhere and deployed and run. But I suspect most users will want to customize things first.

**Comment by fgypas** [comment]
Ah, ok sorry. I relied on the following:

```bash
usage: snakeface [-h] [--version] [--noreload] [--verbosity {0,1,2,3}]
                 [--workdir [WORKDIR]] [--auth {token}] [--port PORT]
                 [--quiet] [--verbose] [--log-disable-color]
                 [--log-use-threads] [--force]
                 [repo] [dest] {notebook} ...
```
and I assumed that `repo` is a github repo and `dest` is the destination where the repo is cloned, and `notebook` is just the notebook mode.

I will try again with a locally cloned pipeline and ping you again.

**Comment by fgypas** [comment]
Great. Thanks a lot! I am following this now.
